name: Version Management

on:
  push:
    branches:
      - main

jobs:
  version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Manual version bump
        run: |
          # Check if VERSION.txt exists and has content
          if [ ! -s VERSION.txt ]; then
            echo "1.0.0" > VERSION.txt
            echo "VERSION.txt was missing, initialized to 0.1.0"
          fi

          VERSION=$(cat VERSION.txt)
          echo "Current version: $VERSION"

          # Decide new version based on commit message
          COMMIT_MESSAGE=$(git log -1 --pretty=%B)
          if [[ "$COMMIT_MESSAGE" == *"[major]"* ]]; then
            NEW_VERSION=$(echo $VERSION | awk -F. '{$1+=1; $2=0; $3=0; print $1"."$2"."$3}')
          elif [[ "$COMMIT_MESSAGE" == *"[minor]"* ]]; then
            NEW_VERSION=$(echo $VERSION | awk -F. '{$2+=1; $3=0; print $1"."$2"."$3}')
          else
            NEW_VERSION=$(echo $VERSION | awk -F. '{$3+=1; print $1"."$2"."$3}')
          fi

          # Update the version file
          echo $NEW_VERSION > VERSION.txt
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add VERSION.txt
          git commit -m "Bump version to $NEW_VERSION"
          git tag $NEW_VERSION
          git push origin main --tags
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
